#!/usr/bin/env python3
"""
Deterministic AGCR calculator.
Reads base→one_shot, one_shot→final, and base→final diff files,
computes AI code one-shot adoption rate and abandonment rate.

Usage:
  python3 calc_agcr.py \
    --repos-json repos_input.json \
    --agcr-observed 1.0 \
    --output /tmp/agcr-{run_id}/agcr-calc.json

repos_input.json format:
  [
    {
      "repo": "bizad_user_benefit_exchange_server",
      "base_to_one_shot_diff": "/path/to/server-base-to-one-shot.diff",
      "one_shot_to_final_diff": "/path/to/server-one-shot-to-target-final.diff",
      "base_to_final_diff": "/path/to/server-base-to-target-final.diff"
    },
    ...
  ]
"""
import argparse
import json
import os
import re
import sys

# Import exclusion rules from filter_excluded_files
_FILTER_DIR = os.path.dirname(os.path.abspath(__file__))
if _FILTER_DIR not in sys.path:
    sys.path.insert(0, _FILTER_DIR)
try:
    from filter_excluded_files import classify_file, split_diff_by_file
    _HAS_FILTER = True
except ImportError:
    _HAS_FILTER = False

# ---------- Constants ----------

# Line-level filter: skip these lines (after strip) when counting +/-
COMMENT_PREFIXES = ("//", "#", "*", "/*", "*/")

# File-level auto-generated markers (case-insensitive substring match)
AUTO_GEN_MARKERS = [
    "@generated",
    "do not edit",
    "autogenerated by",
    "auto-generated",
    "code generated",
    "autogenerated by thrift",   # Thrift stub: "// Autogenerated by Thrift Compiler"
    "generated by the protocol buffer compiler",  # protobuf stub
    "generated by mapstruct",   # mapstruct
]

# File extension whitelist
EXT_WHITELIST = {
    ".java", ".kt", ".scala", ".py", ".js", ".ts", ".jsx", ".tsx",
    ".go", ".rs", ".c", ".cpp", ".h", ".cs", ".rb", ".php",
    ".swift", ".sh", ".bash", ".sql", ".xml", ".yaml", ".yml",
    ".properties", ".gradle", ".tf", ".proto", ".thrift",
}

# Excluded file reasons that should be filtered from AGCR calculation
EXCLUDED_REASONS = {"doc_only", "test_file", "auto_generated", "config_only", "whitespace", "auto_import"}

# Diff header patterns
RE_FILE_HEADER = re.compile(r'^diff --git "?a/(.+?)"? "?b/(.+?)"?\s*$')
RE_NEW_FILE = re.compile(r'^new file mode')
RE_DELETED_FILE = re.compile(r'^deleted file mode')
RE_RENAME = re.compile(r'^rename to (.+)')
RE_COPY = re.compile(r'^copy to (.+)')
RE_BINARY = re.compile(r'^Binary files')


def should_skip_line(line: str) -> bool:
    """Line-level filter: skip empty and comment lines."""
    stripped = line.strip()
    if not stripped:
        return True
    for prefix in COMMENT_PREFIXES:
        if stripped.startswith(prefix):
            return True
    return False


def is_auto_generated(added_lines: list) -> bool:
    """File-level filter: check first ~20 added lines for auto-gen markers."""
    sample = "\n".join(added_lines[:20]).lower()
    for marker in AUTO_GEN_MARKERS:
        if marker.lower() in sample:
            return True
    return False


def get_file_ext(filepath: str) -> str:
    """Get lowercase file extension."""
    _, ext = os.path.splitext(filepath)
    return ext.lower()


def _is_file_excluded(filepath: str, file_diff_content: str) -> bool:
    """Check if a file should be excluded from AGCR calculation.

    Uses filter_excluded_files.classify_file if available (comprehensive rules:
    doc_only, test_file, auto_generated, config_only, whitespace, auto_import).
    Falls back to built-in extension whitelist + auto-gen markers if not.
    """
    if _HAS_FILTER:
        excluded, reason, _detail = classify_file(filepath, file_diff_content)
        if excluded and reason in EXCLUDED_REASONS:
            return True
        return False
    # Fallback: legacy extension whitelist check
    ext = get_file_ext(filepath)
    if ext not in EXT_WHITELIST:
        return True
    return False


def parse_diff(diff_content: str, count_added: bool = True, count_removed: bool = False):
    """
    Parse a unified diff file and count effective + or - lines per file.

    Excludes test files, config files, doc files, auto-generated files,
    whitespace-only changes, and import-only changes from counting.

    Args:
        diff_content: Full text content of the .diff file
        count_added: If True, count + lines (for one_shot_lines)
        count_removed: If True, count - lines (for removed_lines)

    Returns:
        dict: {filepath: line_count} for counted lines
    """
    results = {}
    current_file = None
    current_added_lines = []  # For auto-gen detection
    skip_current_file = False
    file_count = 0
    # Track per-file diff content for exclusion check
    current_file_diff_start = 0
    all_lines = diff_content.splitlines()

    i = 0
    while i < len(all_lines):
        line = all_lines[i]

        # Detect file boundary
        m = RE_FILE_HEADER.match(line)
        if m:
            # Finalize previous file
            if current_file and not skip_current_file:
                # Check auto-generated for added counting (legacy fallback only)
                if count_added and not _HAS_FILTER and is_auto_generated(current_added_lines):
                    file_count = 0
                results[current_file] = file_count

            # Start new file
            current_file = m.group(2)  # b/ path
            current_added_lines = []
            skip_current_file = False
            file_count = 0
            current_file_diff_start = i

            # Check exclusion via filter_excluded_files rules
            if _HAS_FILTER:
                # Build this file's full diff content for classify_file
                file_end = i + 1
                while file_end < len(all_lines) and not RE_FILE_HEADER.match(all_lines[file_end]):
                    file_end += 1
                file_diff_content = "\n".join(all_lines[current_file_diff_start:file_end])
                if _is_file_excluded(current_file, file_diff_content):
                    skip_current_file = True
            else:
                # Fallback: extension whitelist
                ext = get_file_ext(current_file)
                if ext not in EXT_WHITELIST:
                    skip_current_file = True

            i += 1
            continue

        # Handle special headers
        if current_file is not None:
            if RE_NEW_FILE.match(line):
                i += 1
                continue
            if RE_DELETED_FILE.match(line):
                # Skip deleted files for added counting, but for removed counting
                # the file's one_shot lines are all "removed"
                skip_current_file = True if count_added else skip_current_file
                i += 1
                continue
            if RE_RENAME.match(line):
                current_file = RE_RENAME.match(line).group(1)
                ext = get_file_ext(current_file)
                skip_current_file = ext not in EXT_WHITELIST
                i += 1
                continue
            if RE_COPY.match(line):
                current_file = RE_COPY.match(line).group(1)
                ext = get_file_ext(current_file)
                skip_current_file = ext not in EXT_WHITELIST
                i += 1
                continue
            if RE_BINARY.match(line):
                skip_current_file = True
                i += 1
                continue
            if line.startswith("\\ No newline at end of file"):
                i += 1
                continue
            if line.startswith("rename from"):
                i += 1
                continue
            if line.startswith("copy from"):
                i += 1
                continue
            if line.startswith("---") or line.startswith("+++"):
                i += 1
                continue
            if line.startswith("@@"):
                i += 1
                continue
            if line.startswith("index "):
                i += 1
                continue
            if line.startswith("similarity index") or line.startswith("dissimilarity index"):
                i += 1
                continue

            # Content lines
            if skip_current_file:
                i += 1
                continue

            if count_added and line.startswith("+") and not line.startswith("+++"):
                content = line[1:]
                current_added_lines.append(content)
                if not should_skip_line(content):
                    file_count += 1
            elif count_removed and line.startswith("-") and not line.startswith("---"):
                content = line[1:]
                if not should_skip_line(content):
                    file_count += 1

        i += 1

    # Finalize last file
    if current_file and not skip_current_file:
        # Check auto-generated for added counting (legacy fallback)
        if count_added and not _HAS_FILTER and is_auto_generated(current_added_lines):
            file_count = 0
        results[current_file] = file_count

    return results


def calc_agcr(repos_input: list, agcr_observed: float = None) -> dict:
    """
    Calculate AGCR from diff files.

    Args:
        repos_input: List of {repo, base_to_one_shot_diff, one_shot_to_final_diff, base_to_final_diff}
        agcr_observed: Observability AGCR value (0-1), optional

    Returns:
        agcr-calc.json content dict with:
          - agcr: one-shot 采纳率 = retained / final_lines
          - abandonment_rate: one-shot 废弃率 = removed / one_shot_lines
    """
    per_repo = []
    grand_one_shot = 0
    grand_removed = 0
    grand_retained = 0
    grand_final = 0
    grand_final_available = True  # False if any repo lacks base_to_final_diff

    for repo_info in repos_input:
        repo = repo_info["repo"]
        b2o_diff_path = repo_info["base_to_one_shot_diff"]
        o2f_diff_path = repo_info["one_shot_to_final_diff"]
        b2f_diff_path = repo_info.get("base_to_final_diff")  # optional

        # Step 6.1: Count one_shot lines from base→one_shot diff
        one_shot_lines = 0
        if os.path.isfile(b2o_diff_path):
            with open(b2o_diff_path, encoding="utf-8", errors="replace") as f:
                diff_content = f.read()
            if diff_content.strip():
                file_counts = parse_diff(diff_content, count_added=True)
                one_shot_lines = sum(file_counts.values())

        # Step 6.2: Count removed lines from one_shot→final diff
        removed_lines = 0
        if os.path.isfile(o2f_diff_path):
            with open(o2f_diff_path, encoding="utf-8", errors="replace") as f:
                diff_content = f.read()
            if diff_content.strip():
                file_counts = parse_diff(diff_content, count_added=False, count_removed=True)
                removed_lines = sum(file_counts.values())

        # Step 6.2b: Count final_lines from base→final diff
        final_lines = None
        if b2f_diff_path and os.path.isfile(b2f_diff_path):
            with open(b2f_diff_path, encoding="utf-8", errors="replace") as f:
                diff_content = f.read()
            if diff_content.strip():
                file_counts = parse_diff(diff_content, count_added=True)
                final_lines = sum(file_counts.values())
        else:
            grand_final_available = False

        # Step 6.3: Calculate adoption rate and abandonment rate
        # Clamp removed to one_shot (removed > one_shot means non-AI code deletion)
        clamped_removed = min(removed_lines, one_shot_lines)
        retained_lines = one_shot_lines - clamped_removed

        # one-shot 采纳率 = retained / final_lines
        if final_lines is not None and final_lines > 0:
            agcr = retained_lines / final_lines
        else:
            agcr = None

        # one-shot 废弃率 = removed / one_shot_lines
        if one_shot_lines > 0:
            abandonment_rate = clamped_removed / one_shot_lines
        else:
            abandonment_rate = None

        per_repo.append({
            "repo": repo,
            "one_shot_lines": one_shot_lines,
            "removed_lines": clamped_removed,
            "removed_raw": removed_lines,  # Raw count before clamping
            "retained_lines": retained_lines,
            "final_lines": final_lines if final_lines is not None else 0,
            "agcr": round(agcr, 6) if agcr is not None else None,
            "abandonment_rate": round(abandonment_rate, 6) if abandonment_rate is not None else None,
            "clamped": removed_lines > one_shot_lines,
        })

        grand_one_shot += one_shot_lines
        grand_removed += clamped_removed
        grand_retained += retained_lines
        if final_lines is not None:
            grand_final += final_lines

    # Grand total
    # one-shot 采纳率 = retained / final_lines
    if grand_final_available and grand_final > 0:
        calculated_agcr = grand_retained / grand_final
    else:
        calculated_agcr = None

    # one-shot 废弃率 = removed / one_shot_lines
    if grand_one_shot > 0:
        calculated_abandonment = grand_removed / grand_one_shot
    else:
        calculated_abandonment = None

    # Step 6.4: Compare with observability
    agcr_consistency = None
    agcr_gap = None
    divergence_reason = None

    if agcr_observed is not None and calculated_agcr is not None:
        agcr_gap = round(abs(calculated_agcr - agcr_observed), 6)
        if agcr_gap <= 0.05:
            agcr_consistency = "consistent"
        else:
            agcr_consistency = "divergent"
            # Build divergence reason
            clamped_repos = [r for r in per_repo if r.get("clamped")]
            reasons = []
            if clamped_repos:
                reasons.append(
                    f"repo(s) {', '.join(r['repo'] for r in clamped_repos)} "
                    f"的 removed_lines 含预存在代码删除（removed_raw > one_shot），已钳制为 one_shot"
                )
            reasons.append(
                "calculated 用 retained/final_lines 行级过滤口径，"
                "observability agcr_overall 可能使用不同统计口径"
            )
            divergence_reason = "; ".join(reasons)

    result = {
        "agcr": round(calculated_agcr, 6) if calculated_agcr is not None else None,
        "abandonment_rate": round(calculated_abandonment, 6) if calculated_abandonment is not None else None,
        "adjusted_agcr": round(calculated_agcr, 6) if calculated_agcr is not None else None,
        "agcr_consistency": agcr_consistency,
        "agcr_observed": agcr_observed,
        "agcr_gap": agcr_gap,
        "per_repo": per_repo,
        "grand_total": {
            "one_shot_lines": grand_one_shot,
            "removed_lines": grand_removed,
            "retained_lines": grand_retained,
            "final_lines": grand_final,
        },
    }

    if divergence_reason:
        result["divergence_reason"] = divergence_reason

    return result


def main():
    ap = argparse.ArgumentParser(description="Calculate AGCR from diff files")
    ap.add_argument("--repos-json", required=True, help="JSON file with repo diff paths")
    ap.add_argument("--agcr-observed", type=float, default=None,
                    help="Observability AGCR value (0-1)")
    ap.add_argument("--output", required=True, help="Output JSON file path")
    args = ap.parse_args()

    with open(args.repos_json, encoding="utf-8") as f:
        repos_input = json.load(f)

    result = calc_agcr(repos_input, args.agcr_observed)

    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(result, f, ensure_ascii=False, indent=2)

    agcr_pct = f"{result['agcr']*100:.1f}%" if result.get("agcr") is not None else "N/A"
    abn_pct = f"{result['abandonment_rate']*100:.1f}%" if result.get("abandonment_rate") is not None else "N/A"
    print(f"[calc_agcr] AGCR (one-shot 采纳率) = {agcr_pct}", file=sys.stderr)
    print(f"[calc_agcr] Abandonment (one-shot 废弃率) = {abn_pct}", file=sys.stderr)
    print(f"[calc_agcr] Written to {args.output}", file=sys.stderr)


if __name__ == "__main__":
    raise SystemExit(main())
