#!/usr/bin/env python3
"""
filter_excluded_files.py — 对 diff 文件做确定性排除预处理。

将 SKILL.md Step 5.2 的 6 类排除规则（doc_only / whitespace / auto_import /
auto_generated / test_file / config_only）从自然语言描述下沉为确定性代码，
SubAgent 在 Hunk 切分前调用本脚本，得到每个物理 hunk 的 excluded 标记和
exclude_reason，然后只在非排除 hunk 上做语义归因。

用法：
  python3 filter_excluded_files.py \
    --diff   /path/to/{repo}-one-shot-to-target-final.diff \
    --output /path/to/{repo}/excluded-hunks.json

输出 JSON 格式：
  {
    "total_files": 32,
    "excluded_files": [
      {"file": "docs/work_status.md", "reason": "doc_only", "detail": "元析流程产物文件"},
      ...
    ],
    "non_excluded_files": ["src/main/java/..."],
    "stats": {"doc_only": 4, "test_file": 2, ...}
  }

排除规则按优先级顺序匹配（一旦命中即停止后续匹配）：
  1. doc_only       — 纯文档文件（.md/.txt/.rst），包括元析流程产物
  2. test_file      — 测试文件（*Test.java / src/test/ 等）
  3. auto_generated — 自动生成代码（@generated / do not edit 等）
  4. config_only    — 仅配置值变更（pom.xml 仅版本号 / application.yml 端口等）
  5. whitespace     — 改动仅含空白符（整个文件级别判断）
  6. auto_import    — 改动仅含 import / package 语句
"""

import argparse
import json
import os
import re
import sys


# ── 1. doc_only ─────────────────────────────────────────────────────────────
DOC_EXTENSIONS = ('.md', '.txt', '.rst', '.adoc', '.asciidoc')

# 元数据/配置类文件（非业务代码）
META_EXTENSIONS = ('.json', '.sql', '.ddl')

# DDL migration 目录
DDL_DIRS = ('db/migration', 'db/migrations', 'flyway', 'liquibase')

YUANXI_DOC_FILES = {
    'work_status.md', 'work-status.md',
    'design_interface.md', 'design-interface.md',
    'gate_test_analysis.md', 'gate-test-analysis.md',
    'clarify-eval-report.md', 'clarify_eval_report.md',
    'baseline_gate.md', 'baseline-gate.md',
    'feature_points.md', 'feature-points.md',
    'evidence.md',
    'constraint_check.md', 'constraint-check.md',
    'repo.md',
}

GENERIC_DOC_FILES = {
    'changelog.md', 'readme.md', 'contributing.md',
    'license', 'authors', 'maintainers',
}


def is_doc_only(filepath, diff_content):
    if not filepath:
        return False, ""
    lower_path = filepath.lower()
    filename = os.path.basename(lower_path)
    if filename in YUANXI_DOC_FILES:
        return True, f"元析流程产物文件 ({filename})"
    if filename in GENERIC_DOC_FILES:
        return True, f"通用文档文件 ({filename})"
    if lower_path.endswith(DOC_EXTENSIONS):
        code_block_re = re.compile(r'```(?:java|kotlin|python|go|typescript|javascript|ts|js|groovy|scala)', re.IGNORECASE)
        if code_block_re.search(diff_content):
            added = [l for l in diff_content.split('\n') if l.startswith('+') and not l.startswith('+++')]
            kw = re.compile(r'\b(public|private|protected|class|interface|def|func|import|package|return|if|for|while|switch|case)\b')
            if any(kw.search(l) for l in added):
                return False, ""
        return True, f"文档文件 ({filename})"
    # JSON 元数据文件（非业务代码）
    if lower_path.endswith('.json'):
        return True, f"JSON 元数据文件 ({filename})"
    # DDL migration SQL 文件
    if lower_path.endswith('.sql'):
        if any(dd in lower_path for dd in DDL_DIRS):
            return True, f"DDL migration 文件 ({filename})"
        return True, f"SQL 文件 ({filename})"
    return False, ""


# ── 2. test_file ────────────────────────────────────────────────────────────
TEST_FILE_PATTERNS = [
    r'.*Test\.java$', r'.*Test\.kt$', r'.*Test\.groovy$',
    r'.*Tests\.java$', r'.*Tests\.kt$', r'.*Tests\.groovy$',
    r'.*TestUtil\.java$', r'.*TestUtils\.java$', r'.*TestFixture\.java$',
    r'.*Spec\.groovy$', r'.*SpockSpec\.groovy$',
    r'.*/src/test/.*', r'.*/src/it/.*', r'.*/src/integration-test/.*',
    r'.*/test/resources/.*', r'.*/src/test/groovy/.*',
    r'.*\.test\.(js|ts|jsx|tsx)$', r'.*\.spec\.(js|ts)$',
    r'.*_test\.go$', r'.*_test\.py$', r'.*test_.*\.py$',
    r'.*\.test\.rs$', r'.*\.spec\.rs$',
    r'.*/__tests__/.*', r'.*/__fixtures__/.*', r'.*/__mocks__/.*',
]
_TEST_RE = re.compile('|'.join(TEST_FILE_PATTERNS))


def is_test_file(filepath):
    if not filepath:
        return False, ""
    if _TEST_RE.match(filepath):
        return True, f"测试文件 ({os.path.basename(filepath)})"
    return False, ""


# ── 3. auto_generated ───────────────────────────────────────────────────────
AUTO_GEN_MARKERS = [
    '@generated', 'do not edit', 'autogenerated by', 'auto-generated',
    'code generated', 'autogenerated by thrift',
    'generated by the protocol buffer compiler',
    'generated by mapstruct', 'generated by protoc',
    '// generated', '// auto-generated', '// autogenerated',
]

def is_auto_generated(filepath, diff_content):
    if not filepath:
        return False, ""
    if filepath.lower().endswith(DOC_EXTENSIONS):
        return False, ""
    lines = diff_content.split('\n')
    check_lines = []
    for line in lines:
        if line.startswith('+++') or line.startswith('---'):
            continue
        if line.startswith('+') or line.startswith(' '):
            check_lines.append(line[1:] if line[:1] in '+ ' else line)
        if len(check_lines) > 30:
            break
    check_text = '\n'.join(check_lines).lower()
    for marker in AUTO_GEN_MARKERS:
        if marker.lower() in check_text:
            return True, f"自动生成代码 (标记: {marker})"
    if filepath.endswith('.java'):
        if 'autogenerated by thrift' in check_text or 'thrift compiler' in check_text:
            return True, "Thrift 自动生成代码"
        if filepath.endswith('Impl.java') and 'generated by mapstruct' in check_text:
            return True, "MapStruct 自动生成代码"
        # Fallback: detect thrift-generated stubs by class name pattern
        # when the diff doesn't include the "Autogenerated by Thrift" header
        _THRIFT_STUB_NAMES = {
            'IFullGiftService', 'FullGiftUserStatusDTO', 'FullGiftUserStatusRes',
        }
        basename_no_ext = os.path.splitext(os.path.basename(filepath))[0]
        if basename_no_ext in _THRIFT_STUB_NAMES:
            return True, f"Thrift 自动生成代码 (类名匹配: {basename_no_ext})"
    return False, ""


# ── 4. config_only ──────────────────────────────────────────────────────────
CONFIG_FILE_PATTERNS = [
    r'.*\.yml$', r'.*\.yaml$', r'.*\.properties$',
    r'.*\.xml$', r'.*\.ini$', r'.*\.conf$', r'.*\.cfg$',
    r'.*\.env$', r'.*\.toml$',
]
_CONFIG_RE = re.compile('|'.join(CONFIG_FILE_PATTERNS))

ARCHITECTURE_PATTERNS = [
    r'<bean\s+class=', r'depends-on=', r'<import\s+resource=',
    r'@Conditional', r'@Profile', r'@Bean', r'@Component', r'@Service',
    r'@Configuration', r'@EnableAutoConfiguration',
]
_ARCH_RE = re.compile('|'.join(ARCHITECTURE_PATTERNS), re.IGNORECASE)

POM_VERSION_CHANGE = re.compile(r'^[+-]\s*<version>.*</version>\s*$')


def is_config_only(filepath, diff_content):
    if not filepath:
        return False, ""
    if not _CONFIG_RE.match(filepath):
        return False, ""
    if _ARCH_RE.search(diff_content):
        return False, ""
    if filepath.endswith('pom.xml'):
        added = [l for l in diff_content.split('\n') if l.startswith('+') and not l.startswith('+++')]
        removed = [l for l in diff_content.split('\n') if l.startswith('-') and not l.startswith('---')]
        all_lines = added + removed
        if all_lines and all(POM_VERSION_CHANGE.match(l) for l in all_lines):
            return True, "pom.xml 仅版本号变更"
    added = [l[1:].strip() for l in diff_content.split('\n') if l.startswith('+') and not l.startswith('+++')]
    removed = [l[1:].strip() for l in diff_content.split('\n') if l.startswith('-') and not l.startswith('---')]
    all_lines = added + removed
    if not all_lines:
        return False, ""
    kv_patterns = [
        re.compile(r'^[\w.\-]+\s*[:=]\s*\S+$'),
        re.compile(r'^<[\w.\-]+>.*</[\w.\-]+>$'),
        re.compile(r'^\s*$'),
        re.compile(r'^#'),
        re.compile(r'^//'),
    ]
    if all(any(p.match(l) for p in kv_patterns) for l in all_lines):
        return True, f"配置文件仅配置值变更 ({os.path.basename(filepath)})"
    return False, ""


# ── 5. whitespace ───────────────────────────────────────────────────────────
def is_whitespace_only(diff_content):
    added = [l[1:] for l in diff_content.split('\n') if l.startswith('+') and not l.startswith('+++')]
    removed = [l[1:] for l in diff_content.split('\n') if l.startswith('-') and not l.startswith('---')]
    if not added and not removed:
        return False, ""
    def strip_ws(s):
        return re.sub(r'\s+', '', s)
    a = sorted(strip_ws(l) for l in added if l.strip())
    r = sorted(strip_ws(l) for l in removed if l.strip())
    if a == r:
        return True, "改动仅含空白符变化"
    if not any(s for s in a) and not any(s for s in r):
        return True, "改动仅含空行变化"
    return False, ""


# ── 6. auto_import ──────────────────────────────────────────────────────────
IMPORT_PATTERNS = [
    re.compile(r'^\s*import\s+', re.IGNORECASE),
    re.compile(r'^\s*package\s+', re.IGNORECASE),
    re.compile(r'^\s*from\s+\S+\s+import\s+', re.IGNORECASE),
    re.compile(r'^\s*#\s*include\s+', re.IGNORECASE),
    re.compile(r'^\s*use\s+', re.IGNORECASE),
]


def is_auto_import_only(diff_content):
    added = [l[1:] for l in diff_content.split('\n') if l.startswith('+') and not l.startswith('+++')]
    removed = [l[1:] for l in diff_content.split('\n') if l.startswith('-') and not l.startswith('---')]
    all_lines = added + removed
    if not all_lines:
        return False, ""
    non_empty = [l for l in all_lines if l.strip()]
    if not non_empty:
        return False, ""
    if all(any(p.match(l) for p in IMPORT_PATTERNS) for l in non_empty):
        return True, "改动仅含 import/package 语句"
    return False, ""


# ── 主逻辑 ──────────────────────────────────────────────────────────────────

def split_diff_by_file(diff_text):
    parts = re.split(r'(?=^diff --git )', diff_text, flags=re.MULTILINE)
    result = []
    for part in parts:
        if not part.strip():
            continue
        m = re.match(r'diff --git "?a/(.+?)"? "?b/(.+?)"?$', part, re.MULTILINE)
        if m:
            result.append((m.group(2), part))
    return result


def classify_file(filepath, file_diff):
    """按优先级顺序匹配排除规则，一旦命中即返回。"""
    excluded, detail = is_doc_only(filepath, file_diff)
    if excluded:
        return True, "doc_only", detail
    excluded, detail = is_test_file(filepath)
    if excluded:
        return True, "test_file", detail
    excluded, detail = is_auto_generated(filepath, file_diff)
    if excluded:
        return True, "auto_generated", detail
    excluded, detail = is_config_only(filepath, file_diff)
    if excluded:
        return True, "config_only", detail
    excluded, detail = is_whitespace_only(file_diff)
    if excluded:
        return True, "whitespace", detail
    excluded, detail = is_auto_import_only(file_diff)
    if excluded:
        return True, "auto_import", detail
    return False, "", ""


def filter_diff(input_diff_path, output_path):
    with open(input_diff_path, encoding='utf-8') as f:
        diff_text = f.read()

    if not diff_text.strip():
        result = {
            "total_files": 0,
            "excluded_files": [],
            "non_excluded_files": [],
            "stats": {},
            "diff_file": input_diff_path,
        }
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(result, f, ensure_ascii=False, indent=2)
        return result

    file_diffs = split_diff_by_file(diff_text)
    excluded_files = []
    non_excluded_files = []
    stats = {}

    for filepath, file_diff in file_diffs:
        excluded, reason, detail = classify_file(filepath, file_diff)
        if excluded:
            excluded_files.append({"file": filepath, "reason": reason, "detail": detail})
            stats[reason] = stats.get(reason, 0) + 1
        else:
            non_excluded_files.append(filepath)

    result = {
        "total_files": len(file_diffs),
        "excluded_files": excluded_files,
        "non_excluded_files": non_excluded_files,
        "stats": stats,
        "diff_file": input_diff_path,
    }

    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(result, f, ensure_ascii=False, indent=2)

    return result


def main():
    ap = argparse.ArgumentParser(
        description="对 diff 文件做确定性排除预处理（doc_only/test_file/auto_generated/config_only/whitespace/auto_import）"
    )
    ap.add_argument("--diff", required=True, help="输入 diff 文件路径")
    ap.add_argument("--output", required=True, help="输出排除结果 JSON 路径")
    args = ap.parse_args()

    result = filter_diff(args.diff, args.output)

    print(f"[filter] diff: {args.diff}")
    print(f"[filter] total files: {result['total_files']}")
    print(f"[filter] excluded: {len(result['excluded_files'])}")
    for reason, count in sorted(result['stats'].items()):
        print(f"[filter]   {reason}: {count}")
    print(f"[filter] non-excluded: {len(result['non_excluded_files'])}")
    print(f"[filter] output: {args.output}")


if __name__ == "__main__":
    main()
